version: "3"
services:
  backend-api:
    container_name: streamysnap_authservice_backend
    platform: linux/amd64
    # image: parinyapt/streamysnap-authservice:v2.5
    image: pobkun/streamysnap-authservice:v1.0
    ports:
      - "${API_PORT}:80"
    networks:
      - default
    environment:
      TZ: Asia/Bangkok
      DATABASE_MYSQL_HOST: db
      DATABASE_MYSQL_DBNAME: ${DB_NAME}
      DATABASE_MYSQL_USERNAME: ${DB_USERNAME}
      DATABASE_MYSQL_PASSWORD: ${DB_PASSWORD}
      DATABASE_TABLE_PREFIX: streamysnap_authservice_
      APP_NAME: StreamySnap Auth Service Production
      APP_BASE_URL: https://services.streamysnap.com
      JWT_SIGN_KEY_AUTHSESSION: production_AUTHSESSION123456789
      JWT_SIGN_KEY_TEMPORARYTOKEN: production_TEMPORARYTOKEN123456789
      JWT_SIGN_KEY_ACCESSTOKEN: production_ACCESSTOKEN123456789
      JWT_SIGN_KEY_REFRESHTOKEN: production_REFRESHTOKEN123456789
networks:
  default:
    name: ${NETWORK_NAME}
    external: true