version: "3"
services:
  db:
    container_name: streamysnap_authservice_database
    image: mariadb:latest
    restart: always
    networks:
      - default
    volumes:
      - ./mariadb/data:/var/lib/mysql
    user: mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    container_name: streamysnap_authservice_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    networks:
      - default
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=256M
networks:
  default:
    name: ${NETWORK_NAME}
    external: true